# Generated by Django 4.2.7 on 2023-12-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='contacto_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='contacto_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='departamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='lugar_envio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
