# Generated by Django 4.2.1 on 2023-12-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andro', '0003_alter_detallescompra_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andro.compra'),
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='andro.producto'),
        ),
    ]
